version: 2.1

parameters:
  build2-verbosity:
    type: integer
    default: 1

jobs:
  build:
    docker:
      - image: cjangus/fedora-42-test-image
    steps:
      - checkout:
          path: repo
      - run:
          name: "Build"
          command: |
            # @todo: presumably there's a way to stash off a list of options to a file and then use a single option for each invocation
            export VERBOSE="<< pipeline.parameters.build2-verbosity >>"
            cd repo
            # @todo: look into build2 config options file
            bdep init --verbose $VERBOSE --no-progress --bpkg-option --trust-yes -C ../out cc config.cxx="clang++ -stdlib=libc++" \
              config.cc.reprocess=true \
              config.cxx.std=experimental config.cxx.features.modules=true
            # @todo: temp experimentation. some builds of heavier repos were timing out, but some comba of verbose output or this suppressed it.
            # something off though, the 10m timeout should only be if the job creates no output, but it looked as if something was blocking the output
            # rather than the clang invocations actually hanging in any way.
            (
              while true; do
              echo "==== $(date) ===="
              top -b -n1 | head -20
              sleep 10
              done
            ) & MONITOR_PID=$!
            bdep update -j 2 --verbose $VERBOSE --no-progress
            kill $MONITOR_PID
  debug:
    docker:
      - image: cjangus/fedora-42-test-image
    steps:
      - run:
          name: Keep container alive for SSH
          command: sleep 1h

workflows:
  build:
    jobs:
      - build
